version: "3.8"

services:


  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME} 

  fake-gcs:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    command: -scheme http        

